### ISSUE TITLE
Error in TamperMonkey

### ISSUE THREAD

**Issue by tiktokfollowed** [lucakonig/fake-g2a-timezone-glitch#1]
Hey,

after I edit the script, i get this error in Tampermonkey editor.
The script does not change the BTC address and its all as normal.

https://imgur.com/a/iR0mgeQ

Script - https://hastebin.com/asehinogaz.md

Thanks 🥉

**Comment by lucakonig** [comment]
Try to copy the script again, and make sure you didn't miss any character.
